Repository Astrotomic/laravel-translatable, pull requests merged in 2019-10, with the labels that each got.

#73 Refactor the test suite initiation
  phpunit.xml
  tests/TestCase.php
  tests/TestsBase.php
Labels: improvement

#80 temp fix unmigrated test classes
  tests/TestsBase.php
Labels: bug

#83 TravisCI
  .circleci/config.yml
  .travis.yml
  README.md
  composer.json
  docs/README.md
  phpunit.xml.dist
Labels: improvement

#86 scopes test
  phpunit.xml.dist
  tests/ScopesTest.php
  tests/factories/CountryFactory.php
  tests/factories/VegetableFactory.php
Labels: improvement

#87 model override test
  tests/EloquentOverrideTest.php
  tests/TestCoreModelExtension.php
Labels: improvement

#88 refactor validation test class
  tests/ValidationTest.php
Labels: improvement

#84 🚧 Test suite translatable
  tests/TranslatableTest.php
  tests/factories/VegetableFactory.php
  tests/migrations/2013_11_28_152610_create_tables.php
  tests/models/Vegetable.php
  tests/models/VegetableTranslation.php
Labels: improvement

#89 remove old seeds
  tests/seeds/AddFreshSeeds.php
Labels: improvement

#81 remove temp test base class
  tests/TestsBase.php
Labels: improvement

#82 credit david
  README.md
  docs/README.md
Labels: documentation

#94 fix multi connection migration
  tests/migrations/2013_11_28_152610_create_tables.php
Labels: bug

#93 drop outdated laravel versions
  .travis.yml
  composer.json
Labels: bug

#95 drop php7.1 support
  .travis.yml
  composer.json
Labels: bug

#91 use static instead of $this for assertions
  tests/EloquentOverrideTest.php
  tests/LocalesTest.php
  tests/ScopesTest.php
  tests/TranslatableTest.php
  tests/ValidationTest.php
Labels: improvement

#92 use void return type for tests
  tests/EloquentOverrideTest.php
  tests/LocalesTest.php
  tests/ScopesTest.php
  tests/TranslatableTest.php
  tests/ValidationTest.php
Labels: improvement
