Repository Astrotomic/laravel-translatable, pull requests merged in 2019-07, with the labels that each got.

#18 Typo: add word to title of example on how to use orWhereTranslationLike
  docs/usage/scopes.md
Labels: documentation

#20 remove addons
  README.md
  docs/README.md
Labels: documentation

#24 fix circleci mysql
  .circleci/config.yml
Labels: bug

#35 Add auto fallback feature
  src/Translatable/Translatable.php
Labels: feature
